name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - name: Bump version
        id: bump_version
        uses: phips28/gh-action-bump-version@v11
        with:
          tag-prefix: v
      - run: npm run build
      - run: zip -r ../../chrome-extension-${{ steps.bump_version.outputs.newVersion }}.zip .
        working-directory: dist/chrome-extension
      - run: zip -r ../../firefox-extension-${{ steps.bump_version.outputs.newVersion }}.zip .
        working-directory: dist/firefox-extension
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.newTag }}
          generate_release_notes: true
          files: |
            chrome-extension-${{ steps.bump_version.outputs.newVersion }}.zip
            firefox-extension-${{ steps.bump_version.outputs.newVersion }}.zip
